name: build deb

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Check cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/roothide/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v4.2.1
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}

      - name: Prepare Theos
        uses: wwg135/theos-action@main

      - name: Build package
        run: |
          rm -f packages/*
          make package FINALPACKAGE=1
          make package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1
          make package THEOS_PACKAGE_SCHEME=roothide FINALPACKAGE=1

      - name: Upload specific Deb packages
        uses: actions/upload-artifact@v4.6.0
        with:
          name: DYYY
          path: ${{ github.workspace }}/packages/*.deb
